name: production-build
on:
  push:
    branches:
      - master
jobs:
  build and cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Restore cache
        if: steps.submodule-one-build-cache.outputs.cache-hit == 'true'
        run: echo 'has cache'
    
